---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: vm-cirros-1
  name: vm-cirros-1
  namespace: test-vms
spec:
  dataVolumeTemplates:
  - metadata:
      name: cirros-dv-1
    spec:
      pvc:
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 1Gi
        storageClassName: infoscale
      source:
        registry:
          url: docker://quay.io/kubevirt/cirros-container-disk-demo:v1.4.0-rc.0
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-cirros-1
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: rootdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
        resources:
          requests:
            memory: 128Mi
      terminationGracePeriodSeconds: 0
      volumes:
      - dataVolume:
          name: cirros-dv-1
        name: rootdisk
      - cloudInitNoCloud:
          userData: |
            #!/bin/sh

            echo 'printed from cloud-init userdata'
        name: cloudinitdisk

