- name: Apply NFD Operator resources
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', '../../templates/veritas/nfd-operator.yaml') | from_yaml_all }}"

- name: Wait for NodeFeatureDiscovery CRD to be available
  kubernetes.core.k8s_info:
    api_version: nfd.openshift.io/v1
    kind: NodeFeatureDiscovery
  register: nfd_crd_check
  retries: 30
  delay: 10
  until: nfd_crd_check.failed is not defined or not nfd_crd_check.failed
  changed_when: false

- name: Apply NodeFeatureDiscovery CR
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', '../../templates/veritas/nfd-cr.yaml') | from_yaml }}"


- name: Apply Cert Manager Operator resources
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', '../../templates/veritas/cert-manager.yaml') | from_yaml_all }}"

- name: Apply Openshift Virtualization resources
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', '../../templates/veritas/virtualization-operator.yaml') | from_yaml_all }}"

- name: Wait for HyperConverged CRD to be available
  kubernetes.core.k8s_info:
    api_version: hco.kubevirt.io/v1beta1
    kind: HyperConverged
  register: hco_crd_check
  retries: 30
  delay: 10
  until: hco_crd_check.failed is not defined or not hco_crd_check.failed
  changed_when: false

- name: Apply Openshift Virtualization CR
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', '../../templates/veritas/hyperconverged.yaml') | from_yaml_all }}"
